global:
  scrape_interval: 5s 

scrape_configs:
  - job_name: 'event-reminder-app'
    static_configs:
      - targets: ['reminder-app-latest.onrender.com']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']